config/routes.rb
Rails.application.routes.draw do
  get 'finder/index'

  get 'finder/alphabetized'

  get 'finder/missing_email'

  resources :customers
  
  
  root :to  =>'customers#index'

end

app/models/customer.rb
class Customer < ActiveRecord::Base
  validates :full_name, :phone, presence:true
  validates :email, uniqueness:true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
  before_action :set_customer, only: [:show, :edit, :update, :destroy]

  # GET /customers
  # GET /customers.json
  def index
    @customers = Customer.all
  end

  # GET /customers/1
  # GET /customers/1.json
  def show
  end

  # GET /customers/new
  def new
    @customer = Customer.new
  end

  # GET /customers/1/edit
  def edit
  end

  # POST /customers
  # POST /customers.json
  def create
    @customer = Customer.new(customer_params)

    respond_to do |format|
      if @customer.save
        format.html { redirect_to @customer, notice: 'Customer was successfully created.' }
        format.json { render :show, status: :created, location: @customer }
      else
        format.html { render :new }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /customers/1
  # PATCH/PUT /customers/1.json
  def update
    respond_to do |format|
      if @customer.update(customer_params)
        format.html { redirect_to @customer, notice: 'Customer was successfully updated.' }
        format.json { render :show, status: :ok, location: @customer }
      else
        format.html { render :edit }
        format.json { render json: @customer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /customers/1
  # DELETE /customers/1.json
  def destroy
    @customer.destroy
    respond_to do |format|
      format.html { redirect_to customers_url, notice: 'Customer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_customer
      @customer = Customer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def customer_params
      params.require(:customer).permit(:full_name, :phone, :email, :image, :notes)
    end
end

app/controllers/finder_controller.rb
class FinderController < ApplicationController
  def index
    @customers = Customer.all
  end

  def alphabetized
    @customers = Customer.order(full_name:asc)
  end

  def missing_email
    @customers = Customer.where("email = """)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/finder_helper.rb
module FinderHelper
end

app/views/customers/_customer.html.erb
<body >
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <div id = name><%= @customer.full_name %></div>
</p>

<p>
  <strong>Image:</strong>
  <%= imgage_tag @customer.image %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @customer.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>


<p>
  <strong>Notes:</strong>
  <%= @customer.notes %>
</p>
</body>
<!--<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>-->

app/views/customers/_form.html.erb
<%= form_for(@customer) do |f| %>
  <% if @customer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@customer.errors.count, "error") %> prohibited this customer from being saved:</h2>

      <ul>
      <% @customer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
<div >
  <div class="field">
    <%= f.label :full_name %><br>
    <%= f.text_field :full_name %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <%= f.text_field :image %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div>
</div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/customers/edit.html.erb
<h1>Editing Customer</h1>

<%= render 'form' %>

<%= link_to 'Show', @customer %> |
<%= link_to 'Back', customers_path %>

app/views/customers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>All Customers</h1>

<div id = "link"><%= link_to 'New Customer', new_customer_path %></div>

<!--<table>
  
  <thead>
    <tr>
      <th>Full name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Image</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>-->

 <!-- <tbody>-->
    <% @customers.each do |customer| %>
    <div id = a_customer>
     <br>
     <div id=name> <%= customer.full_name %></div><br>
       <%= image_tag customer.image %><br>
       <strong>Phone:</strong> <%= customer.phone %><br></strong>
       <strong>Email:</strong> <%= customer.email %><br></strong>
       <strong>Notes:</strong> <%= customer.notes %><br></strong>
       <br>
       
        </div>
        
        
        
        
      <!-- <%= link_to 'Show', customer %>
        <%= link_to 'Edit', edit_customer_path(customer) %>
        <%= link_to 'Destroy', customer, method: :delete, data: { confirm: 'Are you sure?' } %>-->
 
    <% end %>
  <!--</tbody>
</table>--><br>

app/views/customers/new.html.erb
<h1>New Customer</h1>

<%= render 'form' %>

<%= link_to 'Back', customers_path %>

app/views/customers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Full name:</strong>
  <%= @customer.full_name %>
</p>

<p>
  <strong>Image:</strong>
  <%= @customer.image %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @customer.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @customer.email %>
</p>


<p>
  <strong>Notes:</strong>
  <%= @customer.notes %>
</p>

<!--<%= link_to 'Edit', edit_customer_path(@customer) %> |
<%= link_to 'Back', customers_path %>-->

app/views/finder/alphabetized.html.erb
<h1>Finder#alphabetized</h1>
<p><% render@customer</p>

app/views/finder/index.html.erb
<h1>Finder#index</h1>
<p><% render@customer %></p>

app/views/finder/missing_email.html.erb
<h1>Finder#missing_email</h1>
<p><% render@customer %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CrmChallenge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
 <div id="container"
<%= yield %>
   
</div>

</body>
</html>